rtlsdr:
  frequency: 433.92e6      # Target frequency in Hz
  sample_rate: 2048000     # Sample rate in Hz
  gain: 20.7               # RF gain in dB
  device_index: 0          # RTL-SDR device index

gps:
  port: "/dev/ttyACM0"     # GPS serial port
  baud_rate: 9600          # Serial communication speed
  timeout: 30s             # GPS fix timeout
  disable: true            # Disable GPS hardware and use manual coordinates
  manual_latitude: 35.53313317 # Manual latitude in decimal degrees (when GPS disabled)
  manual_longitude: -97.62130200 # Manual longitude in decimal degrees (when GPS disabled)  
  manual_altitude: 365.0     # Manual altitude in meters (when GPS disabled)



collection:
  duration: 60s            # Collection duration
  output_dir: "./data"     # Output directory
  file_prefix: "argus"     # File naming prefix
  synced_start: true       # Enable synchronized start based on epoch time

logging:
  level: "info"            # Log level (debug, info, warn, error)
  file: "argus.log"        # Log file path
